version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:  
      - .env
  db:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      